### ISSUE TITLE
Question: InitGuard

### ISSUE THREAD

**Issue by GregOnNet** [mhoyer/ng-routing-playground#1]
Hey Marci,

I read the description of your repository.
In many projects, I see that data is initialized using a _Guard_.

As far as I know, this can delay the navigation depending on how long the asynchronous operation will take.
What benefits do you see in using a _Guard_ instead of letting the _DashboarComponent_ handle the loading process instrumenting a Service or the Redux Store?

```
# README.md
The InitGuard will asynchronously initialize application state (before activating the ShellComponent and its child routes)
When InitGuard.canActivate() succeeds the child route /dashboard will be activated. This will initialize DashboardComponent and attach it to the DOM.
```

**Comment by mhoyer** [comment]
It's somehow related to our original implementation of an `InitializationService` and `AuthInitService` we have in our large project. The solution which was implemented there was even worse IMHO. It hides main `AppComponent` parts with `ngIf` while awaiting those async initializers to return HTTP responses that will toggle a boolean flag:
```
<ng-container *ngIf="hasLoggedIn">
    <x-modal-dialog></x-modal-dialog>
</ng-container>

<div class="container">
    <x-error-dialog></x-error-dialog>
    <header>
        <x-navigation *ngIf="hasLoggedIn"></x-navigation>
    </header>
    <main>
        <router-outlet></router-outlet>
    </main>
</div>
```

IMHO **this** feels totally wrong in a first place. Hence, this repo here is just an intermediate step to get out of that mess. 😉 

But I also agree with you that awaiting for initial data to return and not showing the application is also bad UX. But the refactoring of our large application code base (🤔 is it already legacy?) would take some efforts.

**Comment by GregOnNet** [comment]
Thanks for your detailed answer. :-)
It was really just a question since many of teams go this way.
I just wanted to know if I miss something. :-D

It seems that you and I have the same understanding of approach demoed in this repository.
